### ISSUE TITLE
Cannot insert link in attachments

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#3815]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

After upgrade from 0.7.6 to 0.8.3, I noticed I cannot insert links in Attachments.
Either there is a problem with SVG checks or the attachment object has wrong type (sorry, I'm not object-oriented programmer, just a user, so can't tell more).
Also tested in 0.9.0 dev version in demo inventree, fails in the same way.

### Steps to Reproduce

1. Create a part
2. Try to add attachment in the form of a link.
3. Error appears, link cannot be added.

### Expected behavior

Well, it should just work :-D

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Official 0.8.3 container from docker. Cannot tell more because the "about Inventree" does not work for me in 0.8.3 (it did in 0.7.6 before I updated).

### Relevant log output

```shell
Type:
AttributeError

Path:
/api/part/attachment/

Info:
'NoneType' object has no attribute 'lower'

Traceback (most recent call last):

File "/root/.local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/root/.local/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
return self.create(request, *args, **kwargs)

File "/home/inventree/InvenTree/InvenTree/mixins.py", line 18, in create
self.perform_create(serializer)

File "/home/inventree/InvenTree/InvenTree/api.py", line 199, in perform_create
attachment = serializer.save()

File "/home/inventree/InvenTree/InvenTree/serializers.py", line 149, in save
super().save(**kwargs)

File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
self.instance = self.create(validated_data)

File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
instance = ModelClass._default_manager.create(**validated_data)

File "/root/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
obj.save(force_insert=True, using=self.db)

File "/home/inventree/InvenTree/InvenTree/models.py", line 388, in save
if self.attachment.name.lower().endswith('.svg'):

AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by MR-DOS** [comment]
OK, so it seems to only affect the attachments. Adding links in Part Manufacturers and Part Suppliers is fine. Modifying websites in Manufacturers also works.

**Comment by SchrodingersGat** [comment]
@MR-DOS thanks for reporting, looks like a pretty clear bug :)
