### ISSUE TITLE
[BUG] module '_distutils_hack' has no attribute 'ensure_shim'

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2483]
After merging master and trying to run the project get an error.

**Comment by SchrodingersGat** [comment]
Did you run `invoke update` after merging master [as per the instructions](https://inventree.readthedocs.io/en/latest/start/update/)?

**Comment by HelgiBergmann** [comment]
Yes, the same error when running `invoke update`.

**Comment by smallsmallstrong** [comment]
1.Find the location of the file(../site-packages/distutils-precedence.pth )
2.Change the content as 'import os; var = 'SETUPTOOLS_USE_DISTUTILS'; enabled = os.environ.get(var, 'stdlib') == 'local'; enabled and __import__('_distutils_hack').add_shim(); '[1]
3. Save the changed file.
[1] https://github.com/mh-sun/4Connect/blob/master/venv/Lib/site-packages/distutils-precedence.pth

**Comment by SchrodingersGat** [comment]
@HelgiBergmann are you running bare-metal install or docker?

@smallsmallstrong is there another way around the problem that does not involve editing source files?

**Comment by HelgiBergmann** [comment]
@SchrodingersGat please send me an example code of this package installed in your env, so I would like to compare it with my files. I think this can resolve the problem.

**Comment by matmair** [comment]
Replacing site-packages content manually is not an acceptable solution. This does not scale and is not an applicable hotfix. Maybe switching the version of disutils helps? As far as I can see we do not even require disutils so maybe something other than InvenTree was installed into the environment?

**Comment by SchrodingersGat** [comment]
If you have setup the install in a clean virtual environment, you should not be seeing this message...

Did you have any luck fixing this, or still causing a problem?

**Comment by SchrodingersGat** [comment]
@HelgiBergmann closing this issue for now, I think it is a problem on your setup. If you find out any more information feel free to re-open
