### ISSUE TITLE
  'str' object has no attribute 'removesuffix' on attempt access to Stock Item, after updating to 12.1

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [inventree/InvenTree#5393]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After updating to 12.1 from 11.4, any attempts to open "Stock item" cause error page. You still can create stock items, but not open it. 

### Steps to Reproduce

1. Create and fill base with parts\stock items on 11.2 verions.
2. Update to 12.1
3. Try to create\open stock item

### Expected behaviour

Stock item page opens.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

Sorry, we already rolled back. Only one, what i know, is python version was 3.8, we try to switch on 3.9 (python alternatives), but application is refused to start at all. 

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Change Error
Error object (194)
HISTORY

Type:
AttributeError
Path:
http://192.168.2.146/stock/item/435/
Info:
'str' object has no attribute 'removesuffix'
When:
Aug. 2, 2023, 10:01 p.m.
Data:
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in status_label
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in <dictcomp>
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/states.py", line 108, in tag
ref_name = cls.__name__.removesuffix('Status')

AttributeError: 'str' object has no attribute 'removesuffix'
```

**Comment by wolflu05** [comment]
Hello @AlxrMironovOldAcc , this is due to your python version, at least 3.9 is required. Duplicate of #5131

**Comment by SchrodingersGat** [comment]
> we try to switch on 3.9 (python alternatives), but application is refused to start at all.

Do you have a log from that?

**Comment by matmair** [comment]
Duplicate of #5131

**Comment by matmair** [comment]
@AlxrMironovOldAcc any further action on this or can we close this? It seems to be related to your Python version - you need at least 3.9 [as documented here](https://docs.inventree.org/en/latest/start/intro/?h=python+3.9#python-requirements).

**Comment by templeofhead** [comment]
I have a similar issue, but a bit different: currently i have inventree v.11 and to update it to current version i installed python 3.10, made it system default. When i activate venv and invoke `pip install -U -r requirements.txt` the process gets interrupted with error:
```
Building wheels for collected packages: rapidfuzz
  Building wheel for rapidfuzz (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for rapidfuzz (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/rapidfuzz
      copying src/rapidfuzz/utils.py -> build/lib.linux-x86_64-cpython-310/rapidfuzz
      copying src/rapidfuzz/__init__.py -> build/lib.linux-x86_64-cpython-310/rapidfuzz
      copying src/rapidfuzz/process.py -> build/lib.linux-x86_64-cpython-310/rapidfuzz
      copying src/rapidfuzz/fuzz.py -> build/lib.linux-x86_64-cpython-310/rapidfuzz
      running egg_info
      writing src/rapidfuzz.egg-info/PKG-INFO
      writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt
      writing top-level names to src/rapidfuzz.egg-info/top_level.txt
      reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
      running build_ext
      building 'rapidfuzz.levenshtein' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/src
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Isrc/rapidfuzz-cpp/src -Isrc/rapidfuzz-cpp/extern -I/opt/inventree/env/include -I/usr/include/python3.10 -c src/py_levenshtein.cpp -o build/temp.linux-x86_64-cpython-310/src/py_levenshtein.o -O3 -std=c++14 -DVERSION_INFO=\"0.7.6\"
      src/py_levenshtein.cpp:5:10: fatal error: Python.h: No such file or directory
          5 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rapidfuzz
Failed to build rapidfuzz
ERROR: Could not build wheels for rapidfuzz, which is required to install pyproject.toml-based projects
```
Could you assist me on this one?

**Comment by matmair** [comment]
When updating the underlying python you need to remove the virtual environment completely and set it up new - venvs are pinned to specific python versions

**Comment by templeofhead** [comment]
I did remove the old venv, created one as per described in docs, proceeded into `/opt/inventree` (which is my default installation location that installer made), activated new venv with `source env/bin/activate` and `invoked pip install -U -r requirements.txt`, the rest you already know.

**Comment by matmair** [comment]
Are you running bare metal or packaged?

**Comment by templeofhead** [comment]
Managed to update, missing python3x-dev was the culprit. 

Also, when i was done with the update, i went to check if everything was present and found an interesting thing: in the build order tab, when i open\create new build order, the spinner after allocated parts keeps spinning indefinitely instead of showing how many of the parts total isnt allocated. 

Same behaviour was present when i exported database and imported it on the fresh vm, same is as with updating current installation. 

Might it be an issue with the db, or am i missing something? 
![spinner](https://github.com/inventree/InvenTree/assets/142637610/76e06e93-19e6-40a1-85de-c4fa48fba91a)

**Comment by matmair** [comment]
This sounds like a different problem. Please keep issues to one per problem - it becomes hard to reference issues once they contain multiple.

**Comment by templeofhead** [comment]
Understood. I'll open another issue, this one is resolved, thanks.
